# Prompt
brew "starship"

# Fuzzy finder and related tools
brew "fzf"
brew "zoxide"

# Plugin manager for zsh
brew "sheldon"

# Interactive Git
brew "tig"

# GitHub repository manager
brew "ghq"

# Raycast
cask "raycast"

# Language version manager
brew "mise"

# Terminal
cask "wezterm"
