name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Allow trusted contributors only
    if: |
      contains(fromJSON('["OWNER", "COLLABORATOR", "CONTRIBUTOR"]'), 
               github.event.pull_request.author_association)
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please review this pull request thoroughly and provide detailed feedback in Japanese.
            
            Focus on:
            - Code quality and best practices
            - Potential bugs or issues  
            - Performance considerations
            - Security implications
            - Test coverage
            
            Please provide inline comments on specific lines of code with categorized feedback:
            - [MUST] Critical issues requiring immediate attention
            - [IMO] Optional suggestions for consideration
            - [nits] Minor style or formatting improvements
            
            Include an overall summary of your review.
                        
          # Remove tool restrictions - let Claude use default tools for PR reviews
          
          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')
